import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    dashboard: "Dashboard",
    courts: "Courts",
    reservations: "Reservations",
    clients: "Clients",
    financials: "Financials",
    settings: "Settings",
    logout: "Logout",
    padelpro_manager: "PadelPro Manager",
    set_name: "Set Name",
    set_display_name: "Set Your Display Name",
    enter_your_name: "Enter your name",
    user_menu: "User menu",
    logout_success: "You have been logged out successfully.",
    logout_error: "An error occurred during logout.",
    name_updated: "Your display name has been updated.",
    welcome_admin: "Welcome Admin to Levels Dashboard",
    welcome_employee: "Welcome Sales to Levels",
    
    // Common Actions
    add: "Add",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    search: "Search",
    filter: "Filter",
    
    // Reservation Form
    add_reservation: "Add Reservation",
    edit_reservation: "Edit Reservation",
    edit_reservation_details: "Edit the details of this reservation",
    client_name: "Client Name",
    court: "Court",
    date: "Date",
    time: "Time",
    duration: "Duration",
    payment_method: "Payment Method",
    cash: "Cash",
    card: "Card",
    wallet: "Wallet",
    total: "Total",
    notes: "Notes",
    
    // Table Headers
    employee: "Employee",
    status: "Status",
    actions: "Actions",
    
    // Fallbacks and dashes
    no_group: "No Group",
    unknown_client: "Unknown Client",
    unknown_court: "Unknown Court",
    empty_dash: "-",
    
    // Messages
    loading: "Loading...",
    no_data: "No data available",
    error: "Error",
    success: "Success",

    // New keys
    new_clients: "New Clients",
    this_week: "This week",
    court_usage: "Court Usage",
    todays_booking_rate: "Today's booking rate",
    active_clients: "Active Clients",
    with_recent_reservations: "With recent reservations",
    todays_reservations: "Today's Reservations",
    live_data: "Live data from Supabase",
    revenue_expenses: "Revenue & Expenses",
    daily_revenue_expenses: "Daily revenue and expenses for the last 7 days",
    add_court: "Add Court",
    add_client: "Add Client",
    new_reservation: "New Reservation",
    revenue_by_court_group: "Revenue by Court Group",
    revenue_breakdown: "Revenue breakdown by court categories",
    academies: "Academies",
    padel: "Padel",
    football: "football",
    others: "Others",
    track: "Track",
    loading_revenue_data: "Loading revenue data...",
    no_revenue_data: "No revenue data available for the selected period.",
    add_new_court: "Add New Court",
    create_new_court_desc: "Create a new court in the Court Management page.",
    navigation: "Navigation",
    redirecting_to_court_management: "Redirecting to Court Management",
    go_to_courts: "Go to Courts",
    revenue: "Revenue",
    expenses: "Expenses",
    add_group: "Add Group",
    group_manager: "Group Manager",
    manage_padel_courts: "Manage Padel Courts",
    manage_padel_reservations: "Manage court reservations",
    schedule: "Schedule",
    
    // Table Headers for ReservationsPage
    sales_admin: "Sales/Admin",
    client: "Client",
    amount: "Amount",
    running_now: "Running Now",
    today: "Today",
    upcoming: "Upcoming",
    past: "Past",
    no_reservations_found: "No reservations found.",
    all: "All",
    date_range: "Date Range",
    single_day: "Single Day",
    pick_a_date: "Pick a date",
    search_reservations_placeholder: "Search reservations...",
    save_changes: "Save Changes",
    manage_clients: "Manage your client database",
    search_clients_placeholder: "Search clients by name, phone or ID...",
    client_id: "Client ID",
    name: "Name",
    phone: "Phone",
    registered: "Registered",
    no_clients_found: "No clients found",
    add_new_client: "Add New Client",
    edit_client: "Edit Client",
    update_client: "Update Client",
    
    // Financials Overview Cards
    todays_revenue: "Today's Revenue",
    todays_expenses: "Today's Expenses",
    total_revenue: "Total Revenue",
    net_profit: "Net Profit",
    total_revenue_for_today: "Total revenue for today",
    total_expenses_for_today: "Total expenses for today",
    all_time_revenue: "All-time revenue",
    total_revenue_minus_expenses: "Total revenue minus expenses",
    recent_transactions: "Recent Transactions",
    recent_expenses: "Recent Expenses",
    overview_of_financial_data: "Overview of financial data",
    overview: "Overview",
    income: "Income",
    summary: "Summary",
    filter_by_court: "Filter by court name...",
    filter_by_client: "Filter by client name...",
    filter_by_group: "Filter by group name...",
    new_sales: "New Sales",
    group: "Group",
    manage_categories: "Manage Categories",
    add_expense: "Add Expense",
    filter_by_expense_name: "Filter by expense name...",
    filter_by_category: "Filter by category...",
    search_expenses: "Search expenses...",
    title: "Title",
    category: "Category",
    add_new_expense: "Add New Expense",
    expense_title_placeholder: "Expense title...",
    no_category: "No Category",
    add_category: "Add Category",
    optional_notes: "Optional notes...",
    sales: "Sales",
    financials_for: "Financials for",
    total_sales_for_day: "Total sales for the day",
    cash_payments: "Cash payments",
    card_payments: "Card payments",
    wallet_payments: "Wallet payments",
    expenses_for_day: "Expenses for the day",
    cash_minus_expenses: "Cash minus expenses",
    court_sale_summary: "Court Sale Summary",
    expenses_for_the_day: "Expenses for the Day",
    pick_a_date_range: "Pick a date range",
    manage_all_court_groups: "Manage all court groups",
    assign_courts: "Assign courts",
    create_new_court_facility: "Add new court facility",
    court_name: "Court Name",
    court_group: "Court Group",
    select_group: "Select group",
    court_name_placeholder: "Court name...",
    create_court: "Create Court",
    group_name: "Group Name",
    group_name_placeholder: "Group name...",
    add_new_group: "Add New Group",
    create_new_court_group: "Create New Court Group",
    edit_group: "Edit Group",
    edit_court: "Edit Court",
    update_court_details: "Update Court Details",
    update_court: "Update Court",
    create_new_reservation: "Create New Reservation",
    select_court: "Select Court",
    start_time: "Start Time",
    end_time: "End Time",
    select_client: "Select Client",
    amount_of_wallet: "Amount of Wallet",
    amount_of_card: "Amount of Card",
    amount_of_cash: "Amount of Cash",
    total_revenue_for: "Total revenue for",
    total_expenses_for: "Total expenses for",
    total_sales_for: "Total sales for",
    net_profit_for: "Net profit for",
    no_expenses_found: "No expenses found",
  },
  ar: {
    // Navigation
    dashboard: "لوحة التحكم",
    courts: "الملاعب",
    reservations: "الحجوزات",
    clients: "العملاء",
    financials: "المالية",
    settings: "الإعدادات",
    logout: "تسجيل الخروج",
    padelpro_manager: "مدير باديل برو",
    set_name: "تعيين الاسم",
    set_display_name: "تعيين اسم العرض الخاص بك",
    enter_your_name: "أدخل اسمك",
    user_menu: "قائمة المستخدم",
    logout_success: "تم تسجيل الخروج بنجاح.",
    logout_error: "حدث خطأ أثناء تسجيل الخروج.",
    name_updated: "تم تحديث اسم العرض الخاص بك.",
    welcome_admin: "مرحبًا أيها المدير في لوحة ليفلز",
    welcome_employee: "مرحبًا موظف المبيعات في لوحة ليفلز",
    
    // Common Actions
    add: "إضافة",
    edit: "تعديل",
    delete: "حذف",
    save: "حفظ",
    cancel: "إلغاء",
    search: "بحث",
    filter: "تصفية",
    
    // Reservation Form
    add_reservation: "إضافة حجز",
    edit_reservation: "تعديل الحجز",
    edit_reservation_details: "تعديل تفاصيل هذا الحجز",
    client_name: "اسم العميل",
    court: "الملعب",
    date: "التاريخ",
    time: "الوقت",
    duration: "المدة",
    payment_method: "طريقة الدفع",
    cash: "نقدي",
    card: "بطاقة",
    wallet: "محفظة",
    total: "المجموع",
    notes: "ملاحظات",
    
    // Table Headers
    employee: "الموظف",
    status: "الحالة",
    actions: "الإجراءات",
    
    // Fallbacks and dashes
    no_group: "بدون مجموعة",
    unknown_client: "عميل غير معروف",
    unknown_court: "ملعب غير معروف",
    empty_dash: "-",
    
    // Messages
    loading: "جاري التحميل...",
    no_data: "لا توجد بيانات",
    error: "خطأ",
    success: "نجاح",

    // New keys
    new_clients: "عملاء جدد",
    this_week: "هذا الأسبوع",
    court_usage: "استخدام الملعب",
    todays_booking_rate: "معدل الحجز اليومي",
    active_clients: "العملاء النشطون",
    with_recent_reservations: "مع حجوزات حديثة",
    todays_reservations: "حجوزات اليوم",
    live_data: "بيانات مباشرة ",
    revenue_expenses: "الإيرادات والمصروفات",
    daily_revenue_expenses: "الإيرادات والمصروفات اليومية لآخر 7 أيام",
    add_court: "إضافة ملعب",
    add_client: "إضافة عميل",
    new_reservation: "حجز جديد",
    revenue_by_court_group: "الإيرادات حسب نوع الملعب",
    revenue_breakdown: "توزيع الإيرادات حسب الفئات",
    academies: "الأكاديميات",
    padel: "البادل",
    football: "كرة القدم",
    others: "أخرى",
    track: "المضمار",
    loading_revenue_data: "جاري تحميل بيانات الإيرادات...",
    no_revenue_data: "لا توجد بيانات إيرادات للفترة المحددة.",
    add_new_court: "إضافة ملعب جديد",
    create_new_court_desc: "قم بإنشاء ملعب جديد من صفحة إدارة الملاعب.",
    navigation: "التنقل",
    redirecting_to_court_management: "يتم التحويل إلى إدارة الملاعب",
    go_to_courts: "اذهب إلى الملاعب",
    revenue: "الإيرادات",
    expenses: "المصروفات",
    add_group: "إضافة مجموعة",
    group_manager: "مدير المجموعات",
    manage_padel_courts: "إدارة ملاعب البادل",
    manage_padel_reservations: "إدارة حجوزات الملاعب",
    schedule: "الجدول",
    
    // Table Headers for ReservationsPage
    sales_admin: "المبيعات/الإدارة",
    client: "العميل",
    amount: "المبلغ",
    running_now: "يعمل الآن",
    today: "اليوم",
    upcoming: "قادمة",
    past: "ماضية",
    no_reservations_found: "لا توجد حجوزات.",
    all: "الكل",
    date_range: "نطاق التاريخ",
    single_day: "يوم واحد",
    pick_a_date: "اختر تاريخًا",
    search_reservations_placeholder: "...ابحث في الحجوزات",
    save_changes: "حفظ التغييرات",
    manage_clients: "إدارة قاعدة بيانات العملاء",
    search_clients_placeholder: "...ابحث عن العملاء بالاسم أو الهاتف أو الرقم",
    client_id: "رقم العميل",
    name: "الاسم",
    phone: "الهاتف",
    registered: "تاريخ التسجيل",
    no_clients_found: "لا يوجد عملاء",
    add_new_client: "إضافة عميل جديد",
    edit_client: "تعديل العميل",
    update_client: "تحديث العميل",
    
    // Financials Overview Cards
    todays_revenue: "إيرادات اليوم",
    todays_expenses: "مصروفات اليوم",
    total_revenue: "إجمالي الإيرادات",
    net_profit: "صافي الربح",
    total_revenue_for_today: "إجمالي الإيرادات لليوم",
    total_expenses_for_today: "إجمالي المصروفات لليوم",
    all_time_revenue: "إجمالي الإيرادات الكلي",
    total_revenue_minus_expenses: "إجمالي الإيرادات ناقص المصروفات",
    recent_transactions: "المعاملات الأخيرة",
    recent_expenses: "المصروفات الأخيرة",
    overview_of_financial_data: "نظرة عامة على البيانات المالية",
    overview: "نظرة عامة",
    income: "الإيرادات",
    summary: "الملخص",
    filter_by_court: "تصفية حسب اسم الملعب...",
    filter_by_client: "تصفية حسب اسم العميل...",
    filter_by_group: "تصفية حسب اسم المجموعة...",
    new_sales: "عملية بيع جديدة",
    group: "المجموعة",
    manage_categories: "إدارة الفئات",
    add_expense: "إضافة مصروف",
    filter_by_expense_name: "تصفية حسب اسم المصروف...",
    filter_by_category: "تصفية حسب الفئة...",
    search_expenses: "ابحث في المصروفات...",
    title: "العنوان",
    category: "الفئة",
    add_new_expense: "إضافة مصروف جديد",
    expense_title_placeholder: "عنوان المصروف...",
    no_category: "بدون فئة",
    add_category: "إضافة فئة",
    optional_notes: "ملاحظات اختيارية...",
    sales: "المبيعات",
    financials_for: "المالية ليوم",
    total_sales_for_day: "إجمالي المبيعات لليوم",
    cash_payments: "مدفوعات نقدية",
    card_payments: "مدفوعات البطاقة",
    wallet_payments: "مدفوعات المحفظة",
    expenses_for_day: "المصروفات لليوم",
    cash_minus_expenses: "النقدي ناقص المصروفات",
    court_sale_summary: "ملخص مبيعات الملاعب",
    expenses_for_the_day: "المصروفات لليوم",
    pick_a_date_range: "اختر نطاق تاريخ",
    manage_all_court_groups: "إدارة جميع مجموعات الملاعب",
    assign_courts: "تعيين الملاعب",
    create_new_court_facility: "إضافة ملعب جديد",
    court_name: "اسم الملعب",
    court_group: "مجموعة الملعب",
    select_group: "اختر المجموعة",
    court_name_placeholder: "اسم الملعب...",
    create_court: "إنشاء ملعب",
    group_name: "اسم المجموعة",
    group_name_placeholder: "اسم المجموعة...",
    add_new_group: "إضافة مجموعة جديدة",
    create_new_court_group: "إنشاء مجموعة ملاعب جديدة",
    edit_group: "تعديل المجموعة",
    edit_court: "تعديل الملعب",
    update_court_details: "تحديث تفاصيل الملعب",
    update_court: "تحديث الملعب",
    create_new_reservation: "إنشاء حجز جديد",
    select_court: "اختر الملعب",
    start_time: "وقت البدء",
    end_time: "وقت الانتهاء",
    select_client: "اختر العميل",
    amount_of_wallet: "مبلغ المحفظة",
    amount_of_card: "مبلغ البطاقة",
    amount_of_cash: "مبلغ النقد",
    total_revenue_for: "إجمالي الإيرادات لـ",
    total_expenses_for: "إجمالي المصروفات لـ",
    total_sales_for: "إجمالي المبيعات لـ",
    net_profit_for: "صافي الربح لـ",
    no_expenses_found: "لا توجد مصروفات.",
    // --- AUTO-GENERATED PLACEHOLDER ARABIC TRANSLATIONS BELOW ---
    // Please replace these with real translations!
    './pages/Index': 'TODO: translate: ./pages/Index',
    './pages/CourtsPage': 'TODO: translate: ./pages/CourtsPage',
    './pages/ReservationsPage': 'TODO: translate: ./pages/ReservationsPage',
    './pages/ClientsPage': 'TODO: translate: ./pages/ClientsPage',
    './pages/FinancialsPage': 'TODO: translate: ./pages/FinancialsPage',
    './pages/SettingsPage': 'TODO: translate: ./pages/SettingsPage',
    './pages/LoginPage': 'TODO: translate: ./pages/LoginPage',
    './pages/AdminSetup': 'TODO: translate: ./pages/AdminSetup',
    './pages/NotFound': 'TODO: translate: ./pages/NotFound',
    ':': 'TODO: translate: :',
    'T': 'TODO: translate: T',
    'id, reservations!inner(*)': 'TODO: translate: id, reservations!inner(*)',
    'date, amount': 'TODO: translate: date, amount',
    '*': 'TODO: translate: *',
    '*, expense_categories(name)': 'TODO: translate: *, expense_categories(name)',
    '*, reservations!inner(id, clients(name), courts!inner(name, court_groups(name)))': 'TODO: translate: *, reservations!inner(id, clients(name), courts!inner(name, court_groups(name)))',
    '09:00': 'TODO: translate: 09:00',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'ar' : 'en');
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
} 