
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://leoiedhyyplsplmjzxfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxlb2llZGh5eXBsc3BsbWp6eGZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyODQyMjMsImV4cCI6MjA2MTg2MDIyM30.hZ_GV7W2SwhvwJnP3upfdCgOQdjoDZadN-zbRmSp6CE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to get the current user
export const getCurrentUser = async () => {
  const { data: { user } } = await supabase.auth.getUser();
  return user;
};

// Helper function to check if current user has the provided role
export const hasRole = async (role: 'admin' | 'employee') => {
  const user = await getCurrentUser();
  if (!user) return false;
  
  const { data, error } = await supabase.rpc('has_role', {
    _user_id: user.id,
    _role: role
  });
  
  if (error) {
    console.error('Error checking role:', error);
    return false;
  }
  
  return !!data;
};

// Helper function to check if the user is an admin
export const isAdmin = async () => {
  return await hasRole('admin');
};

// Helper function to check if the user is an employee
export const isEmployee = async () => {
  return await hasRole('employee');
};
